## Real Estate - Price Predictor

In [1]:
import pandas as pd

In [2]:
housing = pd.read_csv("dataset1.csv")

In [3]:
housing.head()

X1 transaction date  X2 house age  X3 distance to the nearest MRT station  \
0             2012.917          32.0                                84.87882   
1             2012.917          19.5                               306.59470   
2             2013.583          13.3                               561.98450   
3             2013.500          13.3                               561.98450   
4             2012.833           5.0                               390.56840   

   X4 number of convenience stores  X5 latitude  X6 longitude  \
0                             10.0     24.98298     121.54024   
1                              9.0     24.98034     121.53951   
2                              5.0     24.98746     121.54391   
3                              5.0     24.98746     121.54391   
4                              NaN     24.97937     121.54245   

   Y house price of unit area  
0                        37.9  
1                        42.2  
2                        47.3  
3                        54.8  
4                        43.1

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 7 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   X1 transaction date                     414 non-null    float64
 1   X2 house age                            414 non-null    float64
 2   X3 distance to the nearest MRT station  414 non-null    float64
 3   X4 number of convenience stores         409 non-null    float64
 4   X5 latitude                             414 non-null    float64
 5   X6 longitude                            414 non-null    float64
 6   Y house price of unit area              414 non-null    float64
dtypes: float64(7)
memory usage: 22.8 KB


In [5]:
housing['X2 house age'].value_counts()

X2 house age
0.0     17
13.6     7
13.3     6
16.2     6
13.2     6
        ..
26.8     1
7.6      1
1.9      1
18.5     1
18.8     1
Name: count, Length: 236, dtype: int64

In [6]:
housing.describe()

X1 transaction date  X2 house age  \
count           414.000000    414.000000   
mean           2013.148971     17.712560   
std               0.281967     11.392485   
min            2012.667000      0.000000   
25%            2012.917000      9.025000   
50%            2013.167000     16.100000   
75%            2013.417000     28.150000   
max            2013.583000     43.800000   

       X3 distance to the nearest MRT station  \
count                              414.000000   
mean                              1083.885689   
std                               1262.109595   
min                                 23.382840   
25%                                289.324800   
50%                                492.231300   
75%                               1454.279000   
max                               6488.021000   

       X4 number of convenience stores  X5 latitude  X6 longitude  \
count                        409.00000   414.000000    414.000000   
mean                           4.09780    24.969030    121.533361   
std                            2.95476     0.012410      0.015347   
min                            0.00000    24.932070    121.473530   
25%                            1.00000    24.963000    121.528085   
50%                            4.00000    24.971100    121.538630   
75%                            6.00000    24.977455    121.543305   
max                           10.00000    25.014590    121.566270   

       Y house price of unit area  
count                  414.000000  
mean                    37.980193  
std                     13.606488  
min                      7.600000  
25%                     27.700000  
50%                     38.450000  
75%                     46.600000  
max                    117.500000

In [7]:
#%matplotlib inlin
#import matplotlib.pyplot as plt
#housing.hist(bins=50, figsize=(20,15))

## Train-Test splitting

In [8]:
import numpy as np
# for learning purpose
'''def split_train_test(data, test_ratio):
    np.random.seed(42)
    shuffle= np.random.permutation(len(data))
    print(shuffle)
    test_set_size = int(len(data)*test_ratio)
    test_indices = shuffle[: test_set_size]
    train_indices = shuffle[test_set_size: ]
    return data.iloc[train_indices], data.iloc[test_indices]'''

'def split_train_test(data, test_ratio):\n    np.random.seed(42)\n    shuffle= np.random.permutation(len(data))\n    print(shuffle)\n    test_set_size = int(len(data)*test_ratio)\n    test_indices = shuffle[: test_set_size]\n    train_indices = shuffle[test_set_size: ]\n    return data.iloc[train_indices], data.iloc[test_indices]'

In [9]:
#train_set, test_set = split_train_test(housing, 0.2)

In [10]:
#print(f" Rows in train set: {len(train_set)}\n Rows in test set: {len(test_set)}\n")

In [11]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(housing, test_size=0.2, random_state=42)
print(f" Rows in train set: {len(train_set)}\n Rows in test set: {len(test_set)}\n")

 Rows in train set: 331
 Rows in test set: 83



In [12]:
# for splitting the parameter appropriately among test and train data
'''from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing, housing['X2 house age']):
    strat_train_set=housing.loc[train_index]
    strat_test_set=housing.loc[test_index]'''

"from sklearn.model_selection import StratifiedShuffleSplit\nsplit = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)\nfor train_index, test_index in split.split(housing, housing['X2 house age']):\n    strat_train_set=housing.loc[train_index]\n    strat_test_set=housing.loc[test_index]"

In [13]:
housing = train_set.copy()

## looking for correlation

In [14]:
# tells how our labels/results are correlated with the features
corr_matrix = housing.corr()

In [15]:
corr_matrix['Y house price of unit area'].sort_values(ascending=False)

Y house price of unit area                1.000000
X4 number of convenience stores           0.554369
X5 latitude                               0.531052
X6 longitude                              0.495413
X1 transaction date                       0.074785
X2 house age                             -0.214238
X3 distance to the nearest MRT station   -0.657009
Name: Y house price of unit area, dtype: float64

In [16]:
from pandas.plotting import scatter_matrix
attributes= ["X3 distance to the nearest MRT station", "X4 number of convenience stores", "Y house price of unit area"]
#scatter_matrix(housing[attributes], figsize=(20,15))

In [17]:
#housing.plot(kind="scatter", x="X3 distance to the nearest MRT station", y="Y house price of unit area", alpha=0.5)

## attribute combinations

In [18]:
#housing["DC"] = housing["X3 distance to the nearest MRT station"]/housing["X4 number of convenience stores"]

In [19]:
#housing["DC"]

In [20]:
housing = train_set.drop("Y house price of unit area", axis=1)
housing_label = train_set["Y house price of unit area"].copy()

## missing attributes

In [21]:
# to take care of missing attributes :
#1. get rid of missing data points
#2. get rid of the whole attributes
#3. set value to some value (0, mean, or median)

In [22]:
#a=housing.dropna(subset=["X4 number of convenience stores"]) #option 1
#a.shape

In [23]:
#housing.drop("X4 number of convenience stores", axis=1) #option 2

In [24]:
median = housing["X4 number of convenience stores"].median()

In [25]:
housing["X4 number of convenience stores"].fillna(median)
#original dataframe stays unchanged

192    7.0
234    4.0
5      3.0
45     8.0
245    5.0
      ... 
71     4.0
106    8.0
270    1.0
348    6.0
102    6.0
Name: X4 number of convenience stores, Length: 331, dtype: float64

In [26]:
housing.describe() # before imputing

X1 transaction date  X2 house age  \
count           331.000000    331.000000   
mean           2013.166683     17.288822   
std               0.281570     11.327281   
min            2012.667000      0.000000   
25%            2012.917000      8.450000   
50%            2013.167000     15.900000   
75%            2013.417000     27.200000   
max            2013.583000     43.800000   

       X3 distance to the nearest MRT station  \
count                              331.000000   
mean                              1059.603962   
std                               1217.929569   
min                                 23.382840   
25%                                289.324800   
50%                                492.231300   
75%                               1442.932500   
max                               6306.153000   

       X4 number of convenience stores  X5 latitude  X6 longitude  
count                       326.000000   331.000000    331.000000  
mean                          4.150307    24.969333    121.533885  
std                           2.965253     0.012484      0.014976  
min                           0.000000    24.932070    121.475160  
25%                           1.000000    24.963010    121.529665  
50%                           4.000000    24.971100    121.539170  
75%                           6.000000    24.978260    121.543480  
max                          10.000000    25.014590    121.566270

In [27]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = "median")
imputer.fit(housing)

SimpleImputer(strategy='median')

In [28]:
imputer.statistics_

array([2013.167  ,   15.9    ,  492.2313 ,    4.     ,   24.9711 ,
        121.53917])

In [29]:
x = imputer.transform(housing)

In [30]:
housing_tr = pd.DataFrame(x, columns=housing.columns)

In [31]:
housing_tr.describe()

X1 transaction date  X2 house age  \
count           331.000000    331.000000   
mean           2013.166683     17.288822   
std               0.281570     11.327281   
min            2012.667000      0.000000   
25%            2012.917000      8.450000   
50%            2013.167000     15.900000   
75%            2013.417000     27.200000   
max            2013.583000     43.800000   

       X3 distance to the nearest MRT station  \
count                              331.000000   
mean                              1059.603962   
std                               1217.929569   
min                                 23.382840   
25%                                289.324800   
50%                                492.231300   
75%                               1442.932500   
max                               6306.153000   

       X4 number of convenience stores  X5 latitude  X6 longitude  
count                       331.000000   331.000000    331.000000  
mean                          4.148036    24.969333    121.533885  
std                           2.942760     0.012484      0.014976  
min                           0.000000    24.932070    121.475160  
25%                           1.000000    24.963010    121.529665  
50%                           4.000000    24.971100    121.539170  
75%                           6.000000    24.978260    121.543480  
max                          10.000000    25.014590    121.566270

## Scikit-learn

primarily, three types of objects
1. estimators - it estimates some parameters based on the dataset e.g. imputer. it has a fit() method and transform() method.
   fit() - fits the dataset and calculates the internal parameters.
2. transformers - takes input and returns output based on the learning from fit()
   it also has convenience function called fit_transform() which fits and transform.
3. predictors - linearRegression model is an example of predictor. fit() and predict() are two common function. it also gives score() function which evaluates the predictions.

## feature scaling

primarily two types of scaling:
1. min-max scaling(normalization)
   (value-min)/(max-min)
   - sklearn provides class called MinMaxScaler
3. standardization:
   (value-mean)/std
   - sklearn provides class called StandardScaler for this   

## creating pipeline

In [32]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy="median")),
    ('std_scalar', StandardScaler()),
])

In [33]:
housing_num_tr = my_pipe.fit_transform(housing)

In [34]:
housing_num_tr.shape

(331, 6)

## selecting a desired model

In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
#model = DecisionTreeRegressor()
#model = LinearRegression()
model = RandomForestRegressor()
model.fit(housing_num_tr, housing_label)

RandomForestRegressor()

In [36]:
some_data = housing.iloc[:5]

In [37]:
some_labels = housing_label.iloc[:5]

In [38]:
prepared_data = my_pipe.transform(some_data)

In [39]:
model.predict(prepared_data)

array([49.105     , 24.696     , 30.018     , 37.93573333, 42.79325   ])

In [40]:
list(some_labels)

[42.7, 23.9, 32.1, 38.3, 40.8]

In [41]:
from sklearn.metrics import mean_squared_error
housing_pred = model.predict(housing_num_tr)
mse = mean_squared_error(housing_label, housing_pred)
rmse = np.sqrt(mse)

In [42]:
rmse

np.float64(3.033755117864283)

## cross validation for evaluation

In [43]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, housing_num_tr, housing_label, scoring="neg_mean_squared_error", cv=10)
rmse_scores = np.sqrt(-scores)

In [44]:
rmse_scores

array([ 7.57502858,  5.57248693,  8.11807311,  9.41165751,  6.15406276,
        8.09306193,  6.39728751,  6.07420045,  7.1234126 , 13.84516733])

In [45]:
def print_scores(scores):
    print("Scores: ", scores)
    print("mean: ", scores.mean())
    print("Standard deviation: ", scores.std())

In [46]:
print_scores(rmse_scores)

Scores:  [ 7.57502858  5.57248693  8.11807311  9.41165751  6.15406276  8.09306193
  6.39728751  6.07420045  7.1234126  13.84516733]
mean:  7.836443869630893
Standard deviation:  2.289990286352119


## saving the model

In [47]:
from joblib import dump, load
dump(model, 'estate.joblib')

['estate.joblib']

## testing the data

In [53]:
x_test = test_set.drop("Y house price of unit area", axis=1)
y_test = test_set["Y house price of unit area"].copy()
x_test_prepared = my_pipe.transform(x_test)
final_predictions = model.predict(x_test_prepared)
final_mse = mean_squared_error(y_test,final_predictions)
final_rmse = np.sqrt(final_mse)
print(final_predictions, list(y_test))


[49.791      38.399      57.4975     32.746      25.994      44.987
 49.06733333 50.77933333 14.459      59.3209     25.958      32.299
 35.1135     14.49       37.554      24.765      39.841      53.3325
 25.696      37.0914     15.68433333 23.221      48.849      46.29314286
 14.03013333 34.747      14.974      58.94041667 50.596      38.025
 20.696      25.164      36.366      25.973      46.26       36.85
 54.514      15.60542857 44.073      51.5068     49.47       41.402
 46.278      38.36       39.974      50.48633333 35.1894     24.54
 48.00266667 46.54       49.009      55.221      39.89       38.318
 39.60833333 16.1617619  36.76466667 27.1105     25.307      52.69533333
 27.569      23.677      16.1617619  14.48       19.761      23.393
 26.298      39.661      36.765      26.795      40.51266667 52.463
 55.0595     49.3475     34.263      37.778      40.246      32.26066667
 41.381      32.025      38.969      48.24133333 27.252     ] [45.1, 42.3, 52.2, 37.3, 22.8, 36.3, 53.

In [49]:
final_rmse

np.float64(5.776020492629922)

In [54]:
prepared_data 

array([[ 1.12832111e-03,  2.34401494e+00, -8.23965189e-01,
         9.70613143e-01, -1.47065968e-01,  4.55057247e-01],
       [ 2.96350853e-01, -8.21281376e-01,  9.51417705e-01,
        -5.03814025e-02, -7.43116969e-01, -1.35592638e+00],
       [-1.77732066e+00, -9.00855865e-01,  9.17224467e-01,
        -3.90712918e-01, -5.04054791e-01, -1.42748297e+00],
       [-2.97651108e-01,  1.70741903e+00, -4.69361158e-01,
         1.31094466e+00,  6.55228815e-02,  7.39277351e-01],
       [ 8.90352813e-01, -8.65489426e-01, -3.45356604e-01,
         2.89950113e-01,  2.60462845e-01,  9.53278370e-01]])

In [55]:
prepared_data[0]

array([ 1.12832111e-03,  2.34401494e+00, -8.23965189e-01,  9.70613143e-01,
       -1.47065968e-01,  4.55057247e-01])

## using the model

In [56]:
from joblib import dump, load
import numpy as np
model = load('estate.joblib')

In [57]:
f_input = np.array([[ 1.12832111e-03,  1.34401494e+00, -8.23965189e-01,  9.70613143e-01,
       -1.47065968e-01,  2.55057247e-01]])
model.predict(f_input)

array([45.131])